[package]
name = "ddr0-watcher"
version = "0.1.0"
authors = ["DDR <d@ddr0.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.0"
tokio = {version="1.2.0", features=["macros"]}
notify-rust = "4"